CREATE TABLE STOCK_QUOTES(
STOCK_SYMBOL VARCHAR(10),
MARKET_DATE DATE,
OPEN DECIMAL(10, 4),
HIGH DECIMAL(10, 4),
LOW DECIMAL(10, 4),
CLOSE DECIMAL(10, 4),
VOLUME INT
);

CREATE TABLE ACCOUNT(
FIRSTNAME VARCHAR(10),
LASTNAME VARCHAR(20),
EMAIL VARCHAR(30),
PHONENUMBER VARCHAR(10),
ACCOUNTNUMBER VARCHAR(10),
TRADERID VARCHAR(5)
);

CREATE TABLE ACCT_CASH_AVAILABLE(
ACCOUNTNUMBER VARCHAR(10),
ASOFDATE DATE,
CASHAVAILABLE NUMERIC(10,2)
);

CREATE TABLE ACCT_POSITIONS(
ACCOUNTNUMBER VARCHAR(10),
TICKERSYMBOL VARCHAR(10),
SECURITYNUM VARCHAR(10),
SECURITYDESC VARCHAR(30),
QUANTITY VARCHAR(30),
LASTPRICE DECIMAL (10,4),
CURRENTPOSVALUE NUMERIC(10,2)
);